service: dad-joke-bot

provider:
  name: aws
  runtime: python3.6
  profile: sam__dev__lambda
  stage: production

package:
  exclude:
    - test/**

functions:
  post_to_twitter:
    handler: handler.post_to_twitter
    events:
      - schedule: rate(6 hours)

plugins:
  - serverless-python-requirements
